### ISSUE TITLE
Diagramas de Ingeniería de Software

### ISSUE THREAD

**Issue by dansimancas** [dansimancas/RegistroAsistencias#13]
Elaborar diagramas para definir la estructura de envío de información a la tabla de asistencias.

Assingees:
Laura Y
Jorge

**Comment by lauraschiatti** [comment]
Use Case diagram
![use case diagram](https://cloud.githubusercontent.com/assets/9830709/7206844/fb335c72-e4fa-11e4-9dea-2c607cf79f79.png)

Sequence diagrams
![save attendance](https://cloud.githubusercontent.com/assets/9830709/7206992/cffe9eda-e4fb-11e4-9766-75a7db6cf277.png)

![show attendances of a course](https://cloud.githubusercontent.com/assets/9830709/7206993/cffebdca-e4fb-11e4-8a48-65ece0830482.png)

![show attendances](https://cloud.githubusercontent.com/assets/9830709/7206995/d002b286-e4fb-11e4-9abe-c4cb541aa8eb.png)

![show courses of a student](https://cloud.githubusercontent.com/assets/9830709/7206994/d0018528-e4fb-11e4-8f7b-662e8a13d774.png)

![show courses of a teacher](https://cloud.githubusercontent.com/assets/9830709/7206997/d0081d16-e4fb-11e4-8da2-f102792faad5.png)

![show info of a course](https://cloud.githubusercontent.com/assets/9830709/7206996/d00425a8-e4fb-11e4-9778-6471144f8ae5.png)

![show info of a student](https://cloud.githubusercontent.com/assets/9830709/7206998/d01145b2-e4fb-11e4-8881-34b06cf53a02.png)

![show info of a teacher](https://cloud.githubusercontent.com/assets/9830709/7206999/d0140f40-e4fb-11e4-8f4e-96c6b12163bc.png)

![show statistics by course](https://cloud.githubusercontent.com/assets/9830709/7207002/d0197106-e4fb-11e4-9109-4cca444d4c70.png)

![show statistics by student by course](https://cloud.githubusercontent.com/assets/9830709/7207001/d01818ec-e4fb-11e4-8122-3a88f2bb411b.png)

![show statistics by student](https://cloud.githubusercontent.com/assets/9830709/7207000/d017cbbc-e4fb-11e4-8b82-f423603b11b0.png)

![show students in a course](https://cloud.githubusercontent.com/assets/9830709/7207004/d0237e44-e4fb-11e4-9fca-b9e604e4fc3c.png)

Activity diagrams

![activity diagrams](https://cloud.githubusercontent.com/assets/9830709/6754969/fdb8d454-ceed-11e4-8b0b-70c92009f213.png)

Components diagram

![components diagram](https://cloud.githubusercontent.com/assets/9830709/7416136/da98828a-ef22-11e4-9953-7de72978a396.png)
