### ISSUE TITLE
Primeras vistas en Android

### ISSUE THREAD

**Issue by dansimancas** [dansimancas/RegistroAsistencias#19]
Joseph y Jorge. 
- Fragments

**Comment by jafuca666** [comment]
Encontre unas ayudas, que puedes ser muy utiles al momento de llamar las asistencias, espero les guste. ¿Que me dicen?
https://github.com/daimajia/AndroidSwipeLayout/wiki/usage

**Comment by JorgeFrancoIbanez** [comment]
podemos basarnos en esto
http://itekblog.com/php-android-conversation-using-json-pt-1/
http://codeoncloud.blogspot.com/2012/11/android-php-json-tutorial.html
