### ISSUE TITLE
Wireframe: visualización para el cliente

### ISSUE THREAD

**Issue by dansimancas** [dansimancas/RegistroAsistencias#3]
Descripción...

**Comment by dansimancas** [comment]
Mejor tú fernando

**Comment by JorgeFrancoIbanez** [comment]
![asistencia alumnos utb-page-001](https://cloud.githubusercontent.com/assets/9043522/6531651/c2b29a10-c408-11e4-8865-776e7e9c386c.jpg)
![asistencia alumnos utb-page-002](https://cloud.githubusercontent.com/assets/9043522/6531652/c2b77486-c408-11e4-969e-e4ec64d17398.jpg)
![asistencia alumnos utb-page-003](https://cloud.githubusercontent.com/assets/9043522/6531654/c2b9491e-c408-11e4-9c16-0b3c3f651fbb.jpg)
![asistencia alumnos utb-page-004](https://cloud.githubusercontent.com/assets/9043522/6531655/c2b9987e-c408-11e4-80ca-05c651523749.jpg)
![asistencia alumnos utb-page-005](https://cloud.githubusercontent.com/assets/9043522/6531656/c2bb914c-c408-11e4-8493-9c89e198be8d.jpg)
![asistencia alumnos utb-page-006](https://cloud.githubusercontent.com/assets/9043522/6531653/c2b80f0e-c408-11e4-9abc-9a9e9f7246a3.jpg)
![asistencia alumnos utb-page-007](https://cloud.githubusercontent.com/assets/9043522/6531657/c2c923b6-c408-11e4-8d2b-8290658fa870.jpg)
![asistencia alumnos utb-page-008](https://cloud.githubusercontent.com/assets/9043522/6531658/c2ca6ca8-c408-11e4-9d94-eb6e8fae16f9.jpg)
![asistencia alumnos utb-page-009](https://cloud.githubusercontent.com/assets/9043522/6531660/c2cdc330-c408-11e4-937d-a09cccc9976b.jpg)
![asistencia alumnos utb-page-010](https://cloud.githubusercontent.com/assets/9043522/6531659/c2ccb83c-c408-11e4-860c-7ee4316521e1.jpg)
![asistencia alumnos utb-page-011](https://cloud.githubusercontent.com/assets/9043522/6531661/c2cfa54c-c408-11e4-8d99-cfce54790f1f.jpg)
![asistencia alumnos utb-page-012](https://cloud.githubusercontent.com/assets/9043522/6531662/c2cfda76-c408-11e4-867b-1c7414e176d4.jpg)
![asistencia alumnos utb-page-013](https://cloud.githubusercontent.com/assets/9043522/6531664/c2dd779e-c408-11e4-8d8b-193815c64ab3.jpg)
![asistencia alumnos utb-page-014](https://cloud.githubusercontent.com/assets/9043522/6531663/c2dd2320-c408-11e4-8958-378cd100aae1.jpg)
![asistencia alumnos utb-page-015](https://cloud.githubusercontent.com/assets/9043522/6531665/c2e07624-c408-11e4-93fd-906a252c3795.jpg)
![asistencia alumnos utb-page-016](https://cloud.githubusercontent.com/assets/9043522/6531666/c2e16d54-c408-11e4-8656-98b6af49a2d0.jpg)
