### ISSUE TITLE
Vistas

### ISSUE THREAD

**Issue by dansimancas** [dansimancas/RegistroAsistencias#4]
Lo que dijo Joseph, él se entiende :P

**Comment by jafuca666** [comment]
Aqui esta la vista para la base de datos, creo que hay que cambiar los nombres, yo los dejo en ingles.

CREATE VIEW estudents as
select
a.nombreasignatura as asignature,
a.NRC as NRC,
d.id as student_id,
d.nombres as names ,
d.apellidos as last_name, 
c.n_estudiantes as numb
from sirius_courses as a, 
sirius_students as d, 
sirius_savioexternal as b, 
sirius_courses_info as c, 
sirius_teachers as e 
where a.docenteid = e.id 
and c.id_curso = a.NRC_PERIODO_KEY 
and b.idnumber = a.NRC_PERIODO_KEY 
and d.id=b.USERNAME
ORDER BY a.NOMBREASIGNATURA ASC

**Comment by dansimancas** [comment]
Gracias Joseph!
