### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by dansimancas** [dansimancas/RegistroAsistencias#5]
Nuevos wireframes

**Comment by JorgeFrancoIbanez** [comment]
![img-6 jpg](https://cloud.githubusercontent.com/assets/9043522/6642630/0f0bd3fc-c974-11e4-825d-1a05531d75ed.png)
![img-7](https://cloud.githubusercontent.com/assets/9043522/6642631/0f0c5d2c-c974-11e4-97ff-3f729805d4d4.jpg)
![img-8 jpg](https://cloud.githubusercontent.com/assets/9043522/6642633/0f0d42c8-c974-11e4-9d69-b8a9086ac8c5.png)
![img-9](https://cloud.githubusercontent.com/assets/9043522/6642632/0f0cf61a-c974-11e4-9c50-26d6f78b3702.jpg)
![img-10 jpg](https://cloud.githubusercontent.com/assets/9043522/6642634/0f0e5d16-c974-11e4-9203-4c56bbef1593.png)
![img-11](https://cloud.githubusercontent.com/assets/9043522/6642629/0f0acdae-c974-11e4-8cdd-669733e30610.jpg)
![img-12 jpg](https://cloud.githubusercontent.com/assets/9043522/6642636/0f663c48-c974-11e4-834b-60bf5978ba57.png)
![img-13](https://cloud.githubusercontent.com/assets/9043522/6642638/0f6bdd74-c974-11e4-9897-2bb4c5789c52.jpg)
![img-14 jpg](https://cloud.githubusercontent.com/assets/9043522/6642637/0f6b7456-c974-11e4-8173-d80341814267.png)
![img-15](https://cloud.githubusercontent.com/assets/9043522/6642639/0f6d1b62-c974-11e4-9664-0997c0ac0452.jpg)

**Comment by JorgeFrancoIbanez** [comment]
![asistencia alumnos utb 3 -19](https://cloud.githubusercontent.com/assets/9043522/6756737/db62897a-cef9-11e4-8ec4-eda1f2f17a14.png)
![asistencia alumnos utb 3 -20](https://cloud.githubusercontent.com/assets/9043522/6756738/db855036-cef9-11e4-9162-f84f05be87ad.png)
![asistencia alumnos utb 3 -21](https://cloud.githubusercontent.com/assets/9043522/6756739/db9649b8-cef9-11e4-8beb-053e3d50d8eb.png)
![asistencia alumnos utb 3 -22](https://cloud.githubusercontent.com/assets/9043522/6756740/db9e0dc4-cef9-11e4-8903-ebae7c65831d.png)
