### ISSUE TITLE
Crear Tabla de Asistencias

### ISSUE THREAD

**Issue by dansimancas** [dansimancas/RegistroAsistencias#9]
Vamos a participar todos pero con la ayuda de nuestro especialista en bases de datos, Joseph :+1:

**Comment by jafuca666** [comment]
Aqui les dejo el codigo SQL que desarrolle para el esquema de las tablas para tomar la asistencia.

--Tabla de asistencia por cursos

CREATE TABLE IF NOT EXISTS `asistencebycourse` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `studentId` varchar(9) NOT NULL,
  `courseid` varchar(15) NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (studentId) 
    REFERENCES sirius_students(Id),
    FOREIGN KEY (courseId) 
    REFERENCES sirius_courses(NRC_PERIODO_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--Tabla de las asistencias

CREATE TABLE IF NOT EXISTS `asistence` 
( `id` int(11) NOT NULL AUTO_INCREMENT,
`abcid` int(11) NOT NULL, 
`asistence` bool NOT NULL, 
`Observations` varchar(255) NOT NULL, 
`date` datetime NOT NULL, 
PRIMARY KEY (`id`), 
FOREIGN KEY (abcId) 
REFERENCES asistencebycourse(Id) ) 
ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1

**Comment by jafuca666** [comment]
![img-20150312-wa0010](https://cloud.githubusercontent.com/assets/8743239/6646054/54ea9136-c98f-11e4-9d86-91b7f0edc7e8.jpg)

**Comment by dansimancas** [comment]
Qué juicio! :+1:

**Comment by jafuca666** [comment]
Nueva estructura, con una sola tabla para las asistencias.

CREATE TABLE Asistence (
  Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  StudentId VARCHAR(9) NOT NULL,
  CourseId VARCHAR(15) NOT NULL,
  Asistence BOOL NOT NULL,
  Observation VARCHAR(255) NULL,
  Date DATETIME NOT NULL,
  PRIMARY KEY(Id));

![asistence](https://cloud.githubusercontent.com/assets/8743239/6658719/6b1cb436-cb40-11e4-9e97-91e7e9b64b7e.png)

**Comment by jairoserrano** [comment]
Ahora si pueden usar las migraciones de Laravel en estos casos...

On Sun, Mar 15, 2015 at 6:25 PM, Joseph Fuentes Cantillo <
notifications@github.com> wrote:

> Nueva estructura, con una sola tabla para las asistencias.
> 
> CREATE TABLE Asistence (
> Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
> StudentId VARCHAR(9) NOT NULL,
> CourseId VARCHAR(15) NOT NULL,
> Asistence BOOL NOT NULL,
> Observation VARCHAR(255) NULL,
> Date DATETIME NOT NULL,
> PRIMARY KEY(Id));
> 
> [image: asistence]
> https://cloud.githubusercontent.com/assets/8743239/6658719/6b1cb436-cb40-11e4-9e97-91e7e9b64b7e.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dansimancas/RegistroAsistencias/issues/9#issuecomment-81291809
> .

## 

_Jairo Enrique Serrano Castañeda_
_Ingeniero de Sistemas - UTB_
_Magister Software Libre - UOC_

**Comment by lauricdd** [comment]
Pudiste crear la relacion con las tablas d cursos y estudiantes? Idestudiante e Idcurso como llaves foraneas?

Date: Sun, 15 Mar 2015 17:35:24 -0700

**Comment by jafuca666** [comment]
CREATE TABLE Attendance (
Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
StudentId VARCHAR(9) NOT NULL,
CourseId VARCHAR(15) NOT NULL,
Attendance int NOT NULL default '3' ,
Date DATETIME NOT NULL,
PRIMARY KEY(Id));

**Comment by dansimancas** [comment]
joseph, cómo vas con el trigger?

**Comment by jafuca666** [comment]
Profesor Jairo dijo en el grupo de WhatsApp que las validaciones se van a hacer desde la api

**Comment by jafuca666** [comment]
Drop table asistence; 
Para borrar la anterior tabla.
